dob/urls.py
from django.urls import path
from . import views

app_name = 'dob'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path('', views.index, name='index'),
    path('welcome/', views.hello, name='welcome'),
]

sprytedemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dob.urls')),
]

dob/models.py
from django.db import models

# Create your models here.

dob/views.py
from datetime import datetime
from django.shortcuts import render


def index(request):
    return render(request, 'dob/hello_user.html')


def hello(request):
    if request.method == 'POST':
        # Reading UI inputs
        name = request.POST['username']
        birth_date = request.POST['datetime']

        days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        weekday = datetime.strptime(birth_date, '%Y-%m-%d').weekday()
        weekday = days[weekday]

        message = f'Hi {name}, you were born on a {weekday}!'
        return render(request, 'dob/welcome_user.html',
            {'message': message, 'baseurl': 'https://deploy-spryte-demo.herokuapp.com/'})

dob/templates/dob/hello_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Stylize Login form -->
<form action="{% url 'dob:welcome' %}" method="POST">
    {% csrf_token %}
    <div class="container"> <!--Style root div with .container class -->
        <h1>Welcome</h1>
        <div class="form-group"> <!--Style second div with .form-group class -->
          <label for="username"><b>Name</b></label>
          <input id="username" class = "form-control" type="text" placeholder="Enter Name" name="username" required> <!--Style input with .form-control class -->
          <label for="datetime"><b>Date of Birth</b></label>
          <input id="datetime" class = "form-control" type="date"  placeholder="Enter DOB" name="datetime" required> <!--Style input with .form-control class -->
        </div>
        <button class="btn btn-primary" type="submit">Submit</button> <!--Style button with .btn and .btn-primary class -->
    </div>
</form>

</body>

dob/templates/dob/welcome_user.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
    .ml-5,
    .mx-5 {
        margin-left: 18rem !important;
    }

    .mt-5,
    .my-5 {
        margin-top: 12rem !important;
    }

    .labelclr {
        background-color: #5477F5;
        color: white;
    }

    .card {
        box-shadow: 0 4px 8px 0 rgb(0 0 0 / 20%);
    }

    button {
        float: right;
    }

    button a {
        color: black;
        /* background-color: #eeeeee; */
        text-decoration: none;
    }
</style>


<div class="container justify-content-center mt-5">
    <div class="card w-50 mt-5 ml-5">
        <div class="card-body">
            <h5 style="font-weight: 500;">{{ message }}</h5>
            <button type="button" class="btn btn-light ml-3"><a href="{{ baseurl }}">Go Back</a></button>
        </div>
    </div>
</div>